- name: Setup Node
uses: actions/setup-node@v4
with:
node-version: 20


- name: Install deps
run: npm install


- name: Build
run: node scripts/fetch_and_build.js


- name: Deploy to GH Pages
uses: peaceiris/actions-gh-pages@v4
with:
github_token: ${{ secrets.GITHUB_TOKEN }}
publish_dir: ./dist
